name: awesome_flutter_shaders
description: awesome flutter shaders, manual migration from https://www.shadertoy.com shaders one by one
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shader_buffers: 1.0.1

  image: ^3.0.1
  cupertino_icons: ^1.0.6
  flutter_shaders: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

  shaders:
    - shaders/6.frag
    - shaders/7.frag
    - shaders/Seascape.frag
    - shaders/CineShader Lava.frag
    - shaders/Phantom Star for CineShader.frag
    - shaders/GLSL ray tracing test.frag
    # - shaders/Mystify Screensaver.frag
    # - shaders/Mystify Screensaver Buffer A.frag
    - shaders/DeathStar.frag
    - shaders/Octagrams.frag
    - shaders/Ray Marching.frag
    - shaders/Ray Marching Part 2.frag
    - shaders/Ray Marching Part 3.frag
    - shaders/Ray Marching Part 4.frag
    - shaders/sincos_3d.frag
    - shaders/Flame.frag
    - shaders/Warping procedural 2.frag
    - shaders/Discoteq 2.frag
    - shaders/fire.frag
    - shaders/Devil Glass.frag
    - shaders/warp.frag
    - shaders/page_curl.frag
    # - shaders/Pudi.frag
    # - shaders/Pudi Common.frag
    - shaders/grayscale.frag
    - shaders/Shader Art Coding Introduction.frag
    - shaders/Quadratic Tetrahedron.frag
    - shaders/Seascape.frag
    - shaders/Starleidoscope.frag
    - shaders/Simple super spherical shading.frag
    # Only simple shader sampling is supported
    # - shaders/The Universe Within.frag
    # uvec3 not supported
    # - shaders/Conways ancestors.frag
    # - shaders/Conways ancestors BufferA.frag
    # Only simple shader sampling is supported.
    # - shaders/Elevated BufferA.frag
    # - shaders/Elevated.frag
    - shaders/UI noise halo.frag
    # work
    - shaders/Noise Lab 3D.frag
    #! not work
    # - shaders/Inside the mandelbulb II BufferA.frag
    # - shaders/Inside the mandelbulb II.frag
    #! for loop not supported
    # - shaders/sincos_3d.frag
    #! other problem
    # - shaders/fractal box in fractal world.frag
    - shaders/Mario World.frag
    #! loop bug
    # - shaders/tm gyroids.frag
    #! uvec3 bug
    # - shaders/inercia intended one.frag
    - shaders/wavyfire.frag
    #! syntax error
    # - shaders/Pentagrama.frag
    #! syntax error
    # - shaders/Butterfly Fractal.frag
    #! runtime error
    # - shaders/The Drive Home.frag
    #! compile error
    # - shaders/magic circle4.frag
    - shaders/Clouds-2D.frag
    - shaders/Palace of Mind.frag
    #! Only simple shader sampling is supported
    # - shaders/Voronoi.frag
    #! Only simple shader sampling is supported
    # - shaders/colorful cosmos spiral.frag
    #! syntax error
    # - shaders/colorful vision.frag
    #! syntax error
    # - shaders/cube in cube2.frag
    #! Only simple shader sampling is supported.
    # - shaders/dodecahedron͏.frag
    # - shaders/dodecahedron͏ BufferA.frag
    # ! Only sampler and position arguments are supported in texture() calls
    # - shaders/Space Curvature.frag
    # ! runtime error
    # - shaders/Space Orb BufferA.frag
    # - shaders/Space Orb.frag
    #! program is too large
    # - shaders/M-O from Wall-E.frag
    #! compile error
    # - shaders/Refractive Polyhedron.frag
    # - shaders/Refractive Polyhedron BufferA.frag
    #! compile error
    # - shaders/TIE Fighters.frag
    #! compile error
    # - shaders/Branches.frag
    # - shaders/Branches BufferA.frag
    # - shaders/Branches BufferB.frag
    # - shaders/Branches BufferC.frag
    # - shaders/Branches BufferD.frag
    #! Only simple shader sampling is supported
    # - shaders/The sun, the sky and the clouds.frag
    # work
    - shaders/stars and cosmos 8.frag
    #! program is too large
    - shaders/Refraction post proc.frag
    - shaders/Refraction post proc BufferA.frag
    - shaders/Refraction post proc BufferB.frag
    #! Only simple shader sampling is supported
    # - shaders/Streamlines Youtube Tutorial.frag
    # - shaders/Streamlines Youtube Tutorial BufferA.frag
    # - shaders/Streamlines Youtube Tutorial BufferB.frag
    - shaders/expansive reaction-diffusion BufferA.frag
    - shaders/expansive reaction-diffusion BufferB.frag
    - shaders/expansive reaction-diffusion BufferC.frag
    - shaders/expansive reaction-diffusion BufferD.frag
    - shaders/expansive reaction-diffusion.frag
    #! compile error
    # - shaders/Dolphin.frag
    #! runtime error
    # - shaders/Where the River Goes.frag
    - shaders/Protoplanet.frag
    - shaders/Protoplanet BufferA.frag
    - shaders/Studiogusto.com Gooey Cover.frag
    #! runtime error for loop bug
    # - shaders/teramorfing eye.frag
    #! runtime error
    # - shaders/Industrial Complex Crossview.frag
    - shaders/Main Sequence Star.frag
    - shaders/Fluid solver.frag
    - shaders/Fluid solver BufferA.frag
    #! runtime error
    # - shaders/Varying metric voronoi POC 2.frag
    #! compile error
    # - shaders/Physically Based Shading.frag
    # - shaders/Physically Based Shading BufferA.frag
    #! compile error: Only simple shader sampling is supported
    # - shaders/Volumetric explosion.frag
    #! compile error: Only simple shader sampling is supported
    # - shaders/Plasma Globe.frag
    #! runtime error
    # - shaders/drifting.frag
    - shaders/Black Hole ODE Geodesic Solver.frag
    #! runtime error: for loop
    # - shaders/Origami.frag
    #! Only simple shader sampling is supported
    # - shaders/Hell.frag
    - shaders/SoundEclipse rpm.frag
    #! runtime error
    # - shaders/Perspex Web Lattice.frag
    #! runtime error
    # - shaders/Sphere Gears.frag
    #! Only simple shader sampling is supported
    # - shaders/Pacman Game.frag
    # - shaders/Pacman Game BufferA.frag
    # - shaders/Pacman Game BufferB.frag
    #! compile error
    # - shaders/Liquid Toy.frag
    # - shaders/Liquid Toy BufferA.frag
    #! compile error
    # - shaders/Multiscale MIP Fluid.frag
    # - shaders/Multiscale MIP Fluid BufferA.frag
    # - shaders/Multiscale MIP Fluid BufferB.frag
    # - shaders/Multiscale MIP Fluid BufferC.frag
    # - shaders/Multiscale MIP Fluid BufferD.frag
    # - shaders/Multiscale MIP Fluid Common.frag
    #! Only simple shader sampling is supported
    # - shaders/Enscape Cube.frag
    # - shaders/Enscape Cube BufferA.frag
    # - shaders/Enscape Cube BufferB.frag
    # - shaders/Enscape Cube BufferC.frag
    #! Only simple shader sampling is supported
    # - shaders/Black Hole Raymarcher 3.frag
    # - shaders/Black Hole Raymarcher 3 BufferA.frag
    # - shaders/Black Hole Raymarcher 3 BufferB.frag
    # - shaders/Black Hole Raymarcher 3 BufferC.frag
    #! runtime bug
    # - shaders/Warped Extruded Skewed Grid.frag
    #! compile error
    # - shaders/Physics engine playground.frag
    # - shaders/Physics engine playground BufferA.frag
    # - shaders/Physics engine playground BufferB.frag
    # - shaders/Physics engine playground BufferC.frag
    # - shaders/Physics engine playground BufferD.frag
    #! Only simple shader sampling is supported
    # - shaders/Paroi Jaune Common.frag
    # - shaders/Paroi Jaune.frag
    # - shaders/Paroi Jaune BufferA.frag
    # - shaders/Paroi Jaune BufferB.frag
    # - shaders/Paroi Jaune BufferC.frag
    #! Only simple shader sampling is supported
    # - shaders/Fork Fluidy flu vec2 725.frag
    # - shaders/Fork Fluidy flu vec2 725 BufferA.frag
    # - shaders/Fork Fluidy flu vec2 725 BufferB.frag
    # - shaders/Fork Fluidy flu vec2 725 BufferC.frag
    # - shaders/Fork Fluidy flu vec2 725 BufferD.frag
    # - shaders/Fork Fluidy flu vec2 725 Common.frag
    #! compile bug: error: '=' :  cannot convert from ' const float' to ' temp 4-component vector of float'
    # - shaders/Fire Fire Common.frag
    # - shaders/Fire Fire.frag
    # - shaders/Fire Fire BufferA.frag
    # - shaders/Fire Fire BufferB.frag
    # - shaders/Fire Fire BufferC.frag
    #! compile error: syntax error, unexpected IDENTIFIER
    # - shaders/Tiny Planet Clouds.frag
    #! Only simple shader sampling is supported
    # - shaders/notebook drawings.frag
    - shaders/black holes and crosses.frag
    - shaders/Pinku.frag
    #! compile error
    # - shaders/Aqua in glass.frag
    # - shaders/Aqua in glass BufferA.frag
    #! runtime error: program is too large
    - shaders/Dive to Cloud.frag
    #! compile error
    # - shaders/Goodbye Dream Clouds.frag
    - shaders/rotate and points circle.frag
    #! compile error: Only simple shader sampling is supported
    # - shaders/Clouds.frag
    #! compile error
    # - shaders/Interstellar video - Black hole.frag
    #! compile error
    # - shaders/Great Red Spot - Faux Fluid Sim.frag
    # - shaders/Great Red Spot - Faux Fluid Sim BufferA.frag
    - shaders/Raymarching Basic.frag
    - shaders/mandelbulb.frag
    #! runtime error: too large
    # - shaders/Protean clouds.frag
    #! runtime error: too large
    # - shaders/Perlin sin sphere.frag
    #! runtime error: for loop mabye can try to fix
    # - shaders/Very fast procedural ocean.frag
    #! compile error
    # - shaders/Ben Day Dots Camera.frag
    # - shaders/Ben Day Dots Camera BufferA.frag
    # - shaders/Ben Day Dots Camera BufferB.frag
    # - shaders/Ben Day Dots Camera Common.frag
    - shaders/Blue.frag
    #! runtime error: for (float Pi = 6.283185482025146484375, d = 0.0; d < Pi; d += (Pi / Directions))
    # - shaders/Gaussian Blur Simple and Fast.frag
    #! Only simple shader sampling is supported
    # - shaders/Portal - iOS AR.frag
    # - shaders/Portal - iOS AR BufferA.frag
    #!  Only simple shader sampling is supported
    # - shaders/Pentagonal Conway's game.frag
    # - shaders/Pentagonal Conway's game BufferA.frag
    #! compile error
    # - shaders/Nebula Explained.frag
    # - shaders/Nebula Explained BufferA.frag
    - shaders/Base warp fBM.frag
    - shaders/Phantom Star for CineShader.frag
    #! runtime error
    # - shaders/Cube lines.frag
    - shaders/Broken Time Portal.frag
    #! program is too large
    # - shaders/Full Spectrum Cyber.frag
    - shaders/cubular.frag
    - shaders/colorful Kaleidoscope 7.frag
    - shaders/star and black hole.frag
    - shaders/MONSTER.frag
    - shaders/FWA logo.frag
    - shaders/Basic How To Use Buffer Demo.frag
    - shaders/Basic How To Use Buffer Demo BufferA.frag
    #! Only sampler and position arguments are supported in texture()
    # - shaders/Jupiter and Io.frag
    # - shaders/Jupiter and Io BufferA.frag
    # - shaders/Jupiter and Io BufferB.frag
    #! runtime error
    # - shaders/Something I Saw at a Rave.frag
    # - shaders/Something I Saw at a Rave BufferA.frag
    #! compile error
    # - shaders/Looping Polyhedron Mirrors.frag
    #! runtime error: program is too large
    # - shaders/Ray Marching Part 6.frag
    #! runtime error
    # - shaders/posterize antialiased.frag
    #! program is too large
    - shaders/Galvanize.frag
    #! compile error
    # - shaders/Filmic mandelbulb animation.frag
    # - shaders/Filmic mandelbulb animation BufferA.frag
    # - shaders/Filmic mandelbulb animation BufferB.frag
    # - shaders/Filmic mandelbulb animation BufferC.frag
    #!runtime error
    # - shaders/Fork mandelbulb rogo1965 883.frag
    - shaders/Mandelbulb - derivative.frag
    #! program is too large
    - shaders/Mandelbulb Deconstructed.frag
    #! runtime error: for loop
    # - shaders/Volumetric Mandelbulb.frag
    #! compile error
    # - shaders/Vortex.frag
    - shaders/fractal pyramid.frag
    - shaders/NotSoGreeeen - Chromatic Hole.frag
    #! compile error
    # - shaders/Mirror Looping w Mouse Control.frag
    # - shaders/Mirror Looping w Mouse Control BufferA.frag
    #! skia: do-while loops are not supported
    - shaders/Mandelbulb 3D Fractal.frag
    - shaders/Menger Sponge.frag
    - shaders/Rainier mood.frag
    #! compile error: only simple shader sampling is supported
    # - shaders/Buoy.frag
    - shaders/Warp Speed 2.frag
    #! Only simple shader sampling is supported
    # - shaders/Canyon.frag
    #! Only simple shader sampling is supported.
    # - shaders/furball.frag
    - shaders/Galaxy of Universes.frag
    - shaders/Inverse Bilinear.frag
    - shaders/Bubbles.frag
    # #! Only simple shader sampling is supported
    # - shaders/Chrome Dino game.frag
    # - shaders/Chrome Dino game BufferA.frag
    - shaders/electron.frag
    #! skia runtime error,but work on impeller
    - shaders/Input Time.frag
    - shaders/Starry planes.frag
    - shaders/Starry planes.frag
    # - shaders/Hex Glitch.frag
    # - shaders/Hex Glitch BufferA.frag
    # - shaders/Hex Glitch BufferB.frag
    # - shaders/Hex Glitch Common.frag
    - shaders/Byt3-daily-013.frag
    #! Only simple shader sampling is supported
    # - shaders/Delaunay SDF To Mesh.frag
    # - shaders/Delaunay SDF To Mesh BufferA.frag
    # - shaders/Delaunay SDF To Mesh BufferB.frag
    # - shaders/Delaunay SDF To Mesh BufferC.frag
    - shaders/ED-209.frag
