name: awesome_flutter_shaders
description: awesome flutter shaders, manual migration from https://www.shadertoy.com shaders one by one
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shader_buffers: 1.1.1

  image: ^3.0.1
  cupertino_icons: ^1.0.6
  flutter_shaders: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

dependency_overrides:
  shader_buffers:
    path: /Users/lori/Desktop/nightmare-space/shader_buffers
# flutter_shaders:
#   path: /Users/nightmare/Desktop/flutter_shaders
# shader_buffers:
#   path: /Users/nightmare/Desktop/shader_buffers

flutter:
  uses-material-design: true
  assets:
    - assets/

  shaders:
    # a
    - shaders/a/Angel.frag

    # b
    # - shaders/Butterfly Fractal.frag
    - shaders/b/Black Hole ODE Geodesic Solver.frag
    - shaders/b/black holes and crosses.frag
    - shaders/b/Blue.frag
    - shaders/b/Broken_Time_Portal.frag
    - shaders/b/Broken.frag
    - shaders/b/Bubbles.frag
    - shaders/b/Byt3-daily-013.frag
    #! Only simple shader sampling is supported
    #! when fix grammar error, show black screen
    - shaders/b/Black Hole Raymarcher 3.frag
    - shaders/b/Black Hole Raymarcher 3 BufferA.frag
    - shaders/b/Black Hole Raymarcher 3 BufferB.frag
    - shaders/b/Black Hole Raymarcher 3 BufferC.frag

    # c
    - shaders/c/CineShader Lava.frag
    - shaders/c/Clouds-2D.frag
    - shaders/c/cubular.frag
    - shaders/c/cobweb.frag
    - shaders/c/colorful cosmos spiral.frag
    - shaders/c/Cube lines.frag
    #! Only simple shader sampling is supported
    - shaders/c/Canyon.frag

    # d
    - shaders/d/DeathStar.frag
    - shaders/d/Devil Glass.frag
    - shaders/d/Dive to Cloud.frag
    - shaders/d/DULL SKULL.frag
    - shaders/d/divergence-free flow curly noise.frag
    - shaders/d/drifting.frag

    # e
    - shaders/e/electron.frag
    - shaders/e/ED-209.frag

    # f
    - shaders/f/fire.frag
    - shaders/f/Flame.frag
    - shaders/f/fractal pyramid.frag
    - shaders/f/FWA logo.frag
    - shaders/f/Fire_3D.frag
    - shaders/f/Full Spectrum Cyber.frag

    # g
    - shaders/g/Galaxy of Universes.frag
    - shaders/g/Galvanize.frag
    - shaders/g/GLSL ray tracing test.frag
    - shaders/g/Ghosts.frag
    - shaders/g/Gradient Flow.frag
    - shaders/g/Goodbye Dream Clouds.frag

    # h
    - shaders/h/HOWTO.frag
    - shaders/h/Hell.frag

    # i
    - shaders/i/Input Time.frag
    - shaders/i/Inverse Bilinear.frag
    # ! just black screen
    # - shaders/i/Inside the mandelbulb II BufferA.frag
    # - shaders/i/Inside the mandelbulb II.frag

    # m
    - shaders/m/Main Sequence Star.frag
    - shaders/m/mandelbulb.frag
    - shaders/m/Mandelbulb - derivative.frag
    - shaders/m/Mandelbulb Deconstructed.frag
    - shaders/m/Mandelbulb 3D Fractal.frag
    - shaders/m/Mario World.frag
    - shaders/m/Menger Sponge.frag
    - shaders/m/MONSTER.frag
    - shaders/m/M-O from Wall-E.frag
    - shaders/m/Mirror Looping w Mouse Control.frag
    - shaders/m/Mirror Looping w Mouse Control BufferA.frag

    # n
    - shaders/n/Noise Lab 3D.frag
    - shaders/n/NotSoGreeeen - Chromatic Hole.frag
    #! compile error
    # - shaders/Nebula Explained.frag
    # - shaders/Nebula Explained BufferA.frag

    # o
    - shaders/o/Octagrams.frag
    - shaders/o/Origami.frag

    # p
    - shaders/p/page_curl.frag
    - shaders/p/Page Curl Effect on Ball.frag
    - shaders/p/Palace of Mind.frag
    - shaders/p/Phantom Star for CineShader.frag
    - shaders/p/Pinku.frag
    - shaders/p/Protoplanet.frag
    - shaders/p/Protoplanet BufferA.frag
    - shaders/p/Perlin sin sphere.frag
    - shaders/p/Protean clouds.frag
    - shaders/p/Perspex Web Lattice.frag
    - shaders/p/Plasma Globe.frag
    - shaders/p/Portal - iOS AR.frag
    - shaders/p/Portal - iOS AR BufferA.frag

    # q
    - shaders/q/Quadratic Tetrahedron.frag

    # r
    - shaders/r/Ray Marching.frag
    - shaders/r/Raymarching Basic.frag
    - shaders/r/Rainier mood.frag
    - shaders/r/rotate and points circle.frag
    - shaders/r/Rainforest.frag
    - shaders/r/Rainforest BufferA.frag

    # s
    - shaders/s/Shock_Wave_with_Saturation.frag
    - shaders/s/Seascape.frag
    - shaders/s/Shader Art Coding Introduction.frag
    - shaders/s/Simple super spherical shading.frag
    - shaders/s/SoundEclipse rpm.frag
    - shaders/s/stars and cosmos 8.frag
    - shaders/s/star and black hole.frag
    - shaders/s/Starry planes.frag
    - shaders/s/Starleidoscope.frag
    - shaders/s/Studiogusto.com Gooey Cover.frag
    - shaders/s/Singularity.frag
    - shaders/s/Sphere Gears.frag

    # t
    - shaders/t/Traced Minkowski Tube.frag
    - shaders/t/Tunnel Cable.frag
    - shaders/t/Tunnel Cylinders.frag
    - shaders/t/TIE Fighters.frag
    - shaders/t/tm gyroids.frag

    # u
    - shaders/u/UI noise halo.frag
    - shaders/u/Undular Substratum.frag

    # v
    - shaders/v/Very fast procedural ocean.frag
    #! Only simple shader sampling is supported
    # - shaders/Voronoi.frag
    #! compile error
    # - shaders/Vortex.frag

    # w
    - shaders/w/wavyfire.frag
    - shaders/w/Warping procedural 2.frag
    - shaders/w/Where the River Goes.frag
    - shaders/w/Warped Extruded Skewed Grid.frag

    # z
    - shaders/z/Zippy Zaps.frag
